server:
  port: 3000


routes:
  - path: /users
    target: http://localhost:4001
    protected: false
    rate_limit:
      requests: 10
      window_seconds: 60
      key_by: ip

  - path: /payments
    target: http://localhost:4002
    protected: true
    rate_limit:
      requests: 5
      window_seconds: 60
      key_by: user_id # uses req.user.id set by auth middleware

